name: fix_it
description: A Flutter application for booking home maintenance and repair services

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.2.0

  # Networking
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Firebase - Temporarily disabled due to compatibility issues
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^6.1.5
  js: ^0.7.2
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0

  # Local Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  uuid: ^4.4.0

  # Utils
  intl: ^0.20.2
  easy_localization: ^3.0.8
  cached_network_image: ^3.3.0
  dartz: ^0.10.1

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9

  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^10.2.1

  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.5.0

  # Payments
  flutter_stripe: ^10.0.0 # Replaced stripe_payment

  # Communication
  url_launcher: ^6.2.1
  share_plus: ^11.1.0

  # Permissions
  permission_handler: ^12.0.1

  # Network Info
  connectivity_plus: ^6.1.4

  # Background Tasks
  flutter_background_service: ^5.0.1

  # Date & Time
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^10.0.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.0
  flutter_driver:
    sdk: flutter
  path: ^1.8.3
  image: ^4.0.21

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

  assets:
    - assets/translations/
    - assets/images/cleaning.png
    - assets/images/electrical.png
    - assets/images/location_pin.png
    - assets/images/logo.png
    - assets/images/painting.png
    - assets/images/plumbing.png
    - assets/images/placeholder_profile.png
    - assets/images/rating_star.png
    - assets/images/verified_badge.png
