// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0YiviGlY43ptSfehjbBVEvNmErQksRE0',
    appId: '1:606950507205:web:abd6914470f7aec65d66ac',
    messagingSenderId: '606950507205',
    projectId: 'fix-it-fe14d',
    authDomain: 'fix-it-fe14d.firebaseapp.com',
    storageBucket: 'fix-it-fe14d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0YiviGlY43ptSfehjbBVEvNmErQksRE0',
    appId: '1:606950507205:android:abd6914470f7aec65d66ac',
    messagingSenderId: '606950507205',
    projectId: 'fix-it-fe14d',
    storageBucket: 'fix-it-fe14d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YiviGlY43ptSfehjbBVEvNmErQksRE0',
    appId: '1:606950507205:ios:abd6914470f7aec65d66ac',
    messagingSenderId: '606950507205',
    projectId: 'fix-it-fe14d',
    storageBucket: 'fix-it-fe14d.firebasestorage.app',
    iosClientId: '606950507205-abc123.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0YiviGlY43ptSfehjbBVEvNmErQksRE0',
    appId: '1:606950507205:ios:abd6914470f7aec65d66ac',
    messagingSenderId: '606950507205',
    projectId: 'fix-it-fe14d',
    storageBucket: 'fix-it-fe14d.firebasestorage.app',
    iosClientId: '606950507205-abc123.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0YiviGlY43ptSfehjbBVEvNmErQksRE0',
    appId: '1:606950507205:windows:abd6914470f7aec65d66ac',
    messagingSenderId: '606950507205',
    projectId: 'fix-it-fe14d',
    storageBucket: 'fix-it-fe14d.firebasestorage.app',
  );
}
